### ISSUE TITLE
...

### ISSUE THREAD

**Issue by AntaresOne** [g7755725/GamerROM-8#2]
"Dude just because wget is in their doesnt mean its from your rom and 2nd of all none if this build is from yours if you have a problem with my development then thats fine, but he released it to tge public and its just for stweaks app. dude do u have a life other then taking 10 mins out of your life to say that, really am i really worth your time to even argue, just because you hate me or dont agree of what i do, and if you dont like it why are you downloadong and installing my rom if you hate me why not go somewhere else and leave my stuff alone instead of using my stuff, no one is forcing you and complaining about my work isnt helping and 3rd of all just because im using a third party kernel doesnt mean its from yours, their are thousands of kernels out there, and apperantly you do not understand a true meaning of open source just because i dont follow full src or gpl doesnt mean im breaking a law if there was i would be in jail right now and as well i dont need to release a src because if any other company dont want to doesnt mean i have to open source is something u build on your free time im not getting paid for it, im just love doing it to kill time so please walk away it aint worth it.."

To answer you since you locked down the other.

I still want to know why there's my modified loki code inside your zip and especially why the unique build.prop strings are the same as my 2 June build.

Me and JDCTeam checked your zips since early June. Result?

You based everything on the 2 June build already zipped and released, without any kind of permission since I denied. We have proofs of this.

Zip modding is not what makes you a real developer, especially stealing work of others and reauthor it as your own, like you did on your own forum and on Facebook

Man, just admit your fault.

Delete EVERYTHING you took from our zips.

**Comment by g7755725** [comment]
For one why and second cant the kernel rewuires it as it was tooken not from.your work its cms loki.sh not yours so back off dude its not like im harming anyone or doing crazy shit like pointing a gun at you make it seem like ur insecure
